packages:
  - 'packages/*'
  - 'demo'
catalog:
  '@types/react': '^19.1.3'
  '@types/react-dom': '^19.1.3'
  '@vitejs/plugin-react': '^4.4.1'
  tsx: ^4.19.4
  tsup: ^8.4.0
  typescript: ^5.8.3
  prettier: ^3.5.3
  vite: ^6.3.5
  globals: '^16.0.0'
  react: '^19.1.0'
  react-dom: '^19.1.0'
