packages:
  - 'packages/*'
  - 'demo'
catalog:
  '@types/react': '^19.0.10'
  '@types/react-dom': '^19.0.4'
  '@vitejs/plugin-react': '^4.3.4'
  tsx: ^4.19.3
  tsup: ^8.4.0
  typescript: ^5.6.3
  prettier: ^3.3.3
  vite: ^6.2.0
  globals: '^15.15.0'
  react: '^19.0.0'
  react-dom: '^19.0.0'
