name: Release

on:
  push:
    branches: ['main']

jobs:
  release:
    name: Release
    if: github.repository == '@picpico-labs/biforst'
    runs-on: ubuntu-latest
    timeout-minutes: 20
    permissions:
      contents: write # to create release (changesets/action)
      issues: write # to post issue comments (changesets/action)
      pull-requests: write # to create pull request (changesets/action)
      id-token: write # to use OpenID Connect token for provenance (changesets/action)
    steps:
      - uses: actions/checkout@v4

      - name: Setup CI
      - uses: ./.github/actions/ci-setup

      - name: Create Release Pull Request or Publish to npm
        uses: changesets/action@v1
        with:
          # this expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
